name: PopulationDensity
main: me.ryanhamshire.PopulationDensity.PopulationDensity
softdepend: [Multiverse-Core, My Worlds, Transporter, MystCraft]
version: ${project.version}
commands:
   visit:
      description: Teleportuje gracza do określonego regionu.
      usage: /odziedz <nick gracza>  lub /odiwedz <nazwa regionu>
      aliases: [visitregion, vr, visitpost, odwiedz, wizyta]
   homeregion:
      description: Teleportuje gracza do jego domowego regionu.
      usage: /dom
      aliases: [gohome, homepost, idzdom, domowyregion]
   sethomeregion:
      description: Ustawia domowy region gracza na miejsce, w którym się znajduje w danym momencie.
      usage: /przeprowadzka
      aliases: [movein, sethomeregion, sethomepost, przeprowadzka, ustawdom, ustawdomowyregion]
   nameregion:
      description: Przypisuje nazwę dla dziczy.
      usage: /nameregion <name>
      permission: populationdensity.nameregion
   renameregion:
      description: Zmienia nazwę regionu.
      usage: /renameregion <name>
      permission: populationdensity.renameregion
   whichregion:
      description: Mówi graczu, w jakim regionie się obecnie znajduje.
      usage: /tenregion
      aliases: [jakiregion, tenregion]
   newestregion:
      description: Teleportuje gracza do najnowszego regionu.
      usage: /najnowszyregion
      aliases: [spawnregion, najnowszyregion, newestregion]
   cityregion:
      description: Teleportuje gracza na spawn serwera.
      usage: /spawn
      aliases: [spawn, spawnregion, cityregion]
   addregion:
      description: Zamyka obecnie otwarty region i otwiera nowy.
      usage: /addregion
      permission: populationdensity.addregion
   randomregion:
      description: Teleportuje Cię do losowego regionu.
      usage: /losowyregion
      aliases: [losregion, losowyregion]
   scanregion:
      description: Skanuje region, w którym się znajdujesz w poszukiwaniu zasobów.
      usage: /ScanRegion
      permission: populationdensity.addregion
   addregionpost:
      description: Generuje spawn regionu w środku twojego regionu.
      usage: /AddRegionPost
      permission: populationdensity.addregion
   invite:
      description: Zaprasza gracza, by odwiedził twoj region.
      usage: /zapros <nazwa gracza>
      alises: [invitetoregion, regioninvite, inviteregion, zapros]
   loginpriority:
      description: Ustawia priorytet logowania dla gracza.
      usage: /LoginPriority <player name> <priority, 0 - 100>
      permission: populationdensity.setloginpriority
   thinentities:
      description: Forces entity thinning to run immediately.
      usage: /thinentities
      permission: populationdensity.forcethinning
   simlag:
      description: Symuluje laggowanie serwera.  Tylko do testowania - NIE UŻYWAĆ!
      usage: /simlag <ticksPerSecond>
      permission: populationdensity.simulatelag
   lag:
      description: Sprawdza laggowanie CPU serwera.
      usage: /lag
   listregions:
      description: Wyświetla nazwy wszystkich dostępnych regionów.
      usage: /listaregionow
      aliases: [regions, regionlist, regionslist, allregions, listaregionow, listareg, dostepneregiony]
      permission: populationdensity.listregions
   sendregion:
      description: Wysyła gracza do jego domowego regionu lub do ustalonego.
      usage: /SendRegion <gracz> <region> (jeśli nie podano nazwy, wysyła go do domu)
      aliases: [sendtoregion]
      permission: populationdensity.sendregion
permissions:
    populationdensity.*:
        description: Grants all administrative privileges.
        children:
            populationdensity.buildbreakanywhere: true
            populationdensity.teleportanywhere: true
            populationdensity.addregion: true
            populationdensity.idle: true
            populationdensity.adminlogin: true
            populationdensity.setloginpriority: true
            populationdensity.forcethinning: true
            populationdensity.sendregion: true
            populationdensity.nameregion: true
            populationdensity.renameregion: true
            populationdensity.unlimitedhoppers: true
    populationdensity.newestregion:
        description: Grants permission to use /NewestRegion.
        default: op
    populationdensity.buildbreakanywhere:
        description: Grants permission to edit anywhere in the managed world, including region posts.
        default: op
    populationdensity.teleportanywhere:
        description: Grants permission to use region-based teleportation from any location.
        default: op
    populationdensity.addregion:
        description: Grants permission to the /addregion command.
        default: op    
    populationdensity.idle:
        description: Grants a player permission to idle (without being kicked).
        default: op
    populationdensity.adminlogin:
        description: Grants a player permission to fill a player slot reserved for administrators.
        default: op
    populationdensity.prioritylogin:
        description: Raises a player's login priority level to 25 of 100.
        default: false
    populationdensity.elitelogin:
        description: Raises a player's login priority level to 50 of 100.
        default: false
    populationdensity.setloginpriority:
        description: Grants a player permission to use /SetLoginPriority.
        default: op
    populationdensity.forcethinning:
        description: Grants a player permission to use /ThinEntities.
        default: op
    populationdensity.sendregion:
        description: Grants a player permission to use /SendRegion.
        default: op
    populationdensity.nameregion:
        description: Grants a player permission to use /NameRegion.
        default: op
    populationdensity.renameregion:
        description: Grants a player permission to use /RenameRegion.
        default: op
    populationdensity.simulatelag:
        description: Grants a player permission to use /SimLag.
        default: op
    populationdensity.listregions:
        description: Grants access to /ListRegions.
        default: true
    populationdensity.unlimitedhoppers:
        description: Players with this permission node ignore the hoppers-per-chunk limit defined in the config file.
        default: op